chore: Rebuild all models with kmc-17.0.329 to address missing low-frequency words
keymanapp/lexical-models pull request #274
Opened 2024-09-09 03:46 UTC by darcywong00

Fixes #246

* Update kmc to latest 17.0.329 stable
* Rebuilds all lexical-models to address missing low-frequency words

Also notes HISTORY.md file of sil.km.ggc for #265

2024-09-09 03:52 UTC, mcdurdin requested changes

2024-09-09 03:52 UTC, mcdurdin commented on experimental/ptg/ptg.nan-latn-tw.taigipoj/HISTORY.md
> +* Rebuild with 17.0.329 compiler
I think this needs to say _why_ we are rebuilding with the updated compiler.

2024-09-10 20:53 UTC, DavidLRowe commented
Waiting for @mcdurdin to review and give approval.

2024-09-15 22:58 UTC, mcdurdin commented
Can we split the compiler version update into its own PR please? Then this becomes just maintenance, and issues such as the sil.lzz.laz update happening simultaneously to this won't have an impact.

2024-09-25 22:05 UTC, mcdurdin approved these changes
Approved with removal of package-lock.json changes

2024-09-25 22:05 UTC, mcdurdin commented on package-lock.json
This file shouldn't be in this PR

2024-09-26 00:27 UTC, merged

2024-09-26 01:37 UTC, darcywong00 commented on package-lock.json
argh - I reverted package-lock.json but pushed to my fork instead of here. Will revert on a follow-on

2024-09-26 14:34 UTC, mcdurdin commented on package-lock.json
Don't worry about it. It doesn't do any harm as it stands.